### ISSUE TITLE
🐛 Bug report: Title player name input doesn't follow dark theme

### ISSUE THREAD

**Issue by Lenni009** [AssistantNMS/WebApp#35]
Everything is dark, only the popup is light.
I'll see if I can find the correct component for this myself and fix it tomorrow, otherwise you can do your magic, magic man
![grafik](https://user-images.githubusercontent.com/91371655/216453743-25cdbf42-dff7-4134-8f83-8e97e76cbcc3.png)

**Comment by Lenni009** [comment]
Searching for the correct scss file is true pain. It's so incredibly hard to debug a compiled website

**Comment by Khaoz-Topsy** [comment]
Ah yeah, this is a tough one. That is a SweetAlert2 modal. So the code to make it popup is from an external library 😅. To make it dark mode you will need to override the styles from that library, there wont be anything in the SCSS 🤔

**Comment by Khaoz-Topsy** [comment]
For the AtlasPass webapp, I think I only needed to include this CSS file https://github.com/NMSCD/AtlasPass/blob/d9a023bcf1b9015939c987441df0bbd7ee0a3da3/index.html#L82

**Comment by Lenni009** [comment]
Hm, the popup component doesn't seem to have any class data (assuming it is the NameFloatingActionButton component). Can component names be used in CSS like regular HTML elements (such as div.class#id {display:block})?

**Comment by Lenni009** [comment]
This also applies to other components like the share and card modal btw

**Comment by Lenni009** [comment]
Needs some adjustments, but it's mostly good
![grafik](https://user-images.githubusercontent.com/91371655/216634222-8a4292ec-a8b1-4dbb-a60a-4a287f5eb2bf.png)

**Comment by Lenni009** [comment]
(this was just with the content of your mentioned CSS file)

**Comment by Khaoz-Topsy** [comment]
Sweet! The Share modal is from the ReactModal package, you can customize its stylings with `.ReactModal__Content` in this file https://github.com/AssistantNMS/WebApp/blob/main/src/scss/custom/_shareButton.scss

**Comment by Khaoz-Topsy** [comment]
Sorry I skimmed over your question, with React you will only know what HTML it renders by going into the component. For example the `<NameFloatingActionButton...` component returns a `<BaseFloatingActionButton...` component which returns an actual HTML element `<button>` wrapped in a `<CustomTooltip..`. But it was all a trick! Because the way that `<NameFloatingActionButton>` is used is that it takes an onClick event handler. In the `titlePresenter.tsx` it uses the `<NameFloatingActionButton>` and supplies the onClick parameter. The function it passes in comes through the props from its container `titlesContainer.tsx`. In `titlesContainer.tsx` the setPlayerName function also calls a setPlayerName function from its props (but that is from dependency injection and should be ignored for this example) but more importantly is that a `getStringDialog`  function is called. Inside that function is the method to open up a SweetAlert2 modal 😋

**Comment by Lenni009** [comment]
the ReactModal has a bunch of inline styles, I can't overwrite them without using a bunch of `!important` statements. I don't really want that

**Comment by Lenni009** [comment]
Is there a reason why different dialogs use different components? Wouldn't it make more sense to make them all use SweetAlert or all ReactModal? This just adds maintenance effort and inconsistency

**Comment by Khaoz-Topsy** [comment]
The main reason is that SweetAlert2 is pretty and has nice animations but does not allow me to put React components in the contents of the modal. Where React modal is a completely modal built for easy use in React. I just had a look at where those style might be coming from and I think I found the culprit https://github.com/AssistantNMS/WebApp/blob/main/src/components/common/dialog/baseDialog.tsx . Looks like the inner part of the modal gets its styles from the `content` property of a styles object 😋

**Comment by Lenni009** [comment]
Ah I see. I'll have a closer look, but I can't effectively test since running `npm run dev` spits out an error (Missing Script: "dev"). I ran `npm i` as it says in the readme

**Comment by Khaoz-Topsy** [comment]
Ah the readme lies, do `npm start` or `npm run start`  😅

**Comment by Lenni009** [comment]
Yep, that worked. Thanks!

**Comment by Lenni009** [comment]
The background color is not defined in the file you linked, but it does change if I add the `backgroundColor` property to the style list in the file

**Comment by Khaoz-Topsy** [comment]
Oh ok, I will check what you did in the PR 😋

**Comment by Lenni009** [comment]
I'm nearly done, only thing I struggle with is the checked checkbox backgrounds. They always stay white when checked for some reason
![grafik](https://user-images.githubusercontent.com/91371655/216677318-d1c8785c-0c80-433a-b2cf-8afbf5eb52b2.png)
