### ISSUE TITLE
Small translation error

### ISSUE THREAD

**Issue by Muhaddil** [AssistantNMS/WebApp#61]
The name for "Datos recuperados" returns  the name in English "Salvaged Data". I don't think it would be intended so that why I'm creating this.
<img width="596" alt="Captura de pantalla 2023-12-30 180814" src="https://github.com/AssistantNMS/WebApp/assets/151466679/43a5b10c-2850-426f-83e2-d8e0e1fc35ae">

**Comment by Muhaddil** [comment]
But it seems that it the catalogue it's ok
<img width="1713" alt="Captura de pantalla 2023-12-30 180959" src="https://github.com/AssistantNMS/WebApp/assets/151466679/e7589923-adec-49d5-88d3-7cc1e52a4402">

**Comment by Muhaddil** [comment]
It still happends in the tech tree, I don't know if this error is somewhere else. Strangely in you click in the item it appears in spanish.
![imagen](https://github.com/AssistantNMS/WebApp/assets/151466679/480e0db2-9068-4bf6-b83e-3c587404e8f9)
![imagen](https://github.com/AssistantNMS/WebApp/assets/151466679/fe4d924f-93b5-423f-b342-8c79f416f478)
Also I'm using the WebAPP.

**Comment by Khaoz-Topsy** [comment]
This should be sorted in the next version 0.39.1, just waiting for it to be deployed 😋

**Comment by Khaoz-Topsy** [comment]
Looks to be working on version 0.39.1 with App Store badges @Muhaddil 😁
