### ISSUE TITLE
Language selection doesn't update instantly

### ISSUE THREAD

**Issue by Lenni009** [AssistantNMS/WebApp#78]
Item name and description language does not update after changing it in the dropdown.
It only updates after a reload.

How to reproduce:
1. Go to Catalogue
2. Click on an item
3. Switch to another language
4. See the item name and desc not changing
5. Rest of the UI does change
6. Reload the page
7. See item name and desc has changed language

Expected:
Update all language items when selected language is changed

**Comment by Khaoz-Topsy** [comment]
Ah thanks for pointing this out, I "fixed" a mechanism in the json service that would reduce the amount of network requests for the json files for similar requests, it does not factor in the current language 🤦‍♂️. Easy fix, will get this out with your other issues from Discord 😋

**Comment by Lenni009** [comment]
This also affects the search results btw.

So if you search for "Reactor", then switch to German, then search for "Reaktor", it doesn't return any results. If you search for "Reactor" though it will show the English item names. Only a reload will yield the correct language results
